version: 2
jobs:
  build:
    environment:
      LD_LIBRARY_PATH: /opt/oracle/instantclient_12_1
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get install libaio1
            sudo mkdir /opt/oracle
            sudo chmod 777 /opt/oracle/
            cd /opt/oracle
            curl -OL https://www.dropbox.com/s/p4tnqhyjjtibsjl/instantclient_install.zip
            sudo unzip instantclient_install.zip
            sudo unzip instantclient-basic-linux.x64-12.1.0.2.0.zip -d /opt/oracle
            sudo unzip instantclient-sdk-linux.x64-12.1.0.2.0.zip -d /opt/oracle
            sudo unzip instantclient-sqlplus-linux.x64-12.1.0.2.0.zip -d /opt/oracle
            cd /opt/oracle/instantclient_12_1 && sudo ln -s libclntsh.so.12.1 libclntsh.so
            sudo mkdir /site
            sudo chmod 777 /site
            mv config/features.yml.circleci config/features.yml



# test:
#   post:
#     - bash <(curl -s https://codecov.io/bash)
